bootstrap: Fix build failure
Add missing mkdir calls. This hopefully fixes a race that can cause
build failures with this error:

 .../bootstrap/server/src/ARCH-x86/mb2.S:12:0:
 fatal error: opening dependency file ARCH-x86/mb2.d: No such file or
 directory

That is because there is SRC += ARCH-x86/mb2.S with no rule to generate
the corresponding build directory.

Change-Id: Iacb80a310c7a00311851ad93f16489fa3f0b582b