same exception specification in declaration and implementation
The declaration and implementation of a function need to have the same
exception specification, otherwise newer Clang versions defaulting to
C++17 fail like

  /bootstrap/server/src/libc_support+.cc:175:7: error:
    'lseek' is missing exception specification 'throw()'

See ticket #999.

Change-Id: I8f81e0265f5249ceb88e8e65a716c2793cd37082