fix Clang build error
Now that "region.h" includes <assert.h>, libc_support+.cc includes
<assert.h> as well. Hence, the __assert_fail() function signature has to
match the signature in <assert.h> -- which requires a `throw()` -- or
rather `noexcept` keyword (the latter is C++11 or newer).

This fixes a Clang build error:

  libc_support+.cc:120:1: error:
    '__assert' is missing exception specification 'throw()'
    __assert(const char *assertion, const char * filename,
    ^

Change-Id: Ibdcb664e5046e5d46812fc2e285b915d89700e1a